version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - gotanda.hs-1
      - linear-ephemeral-data-structure
      - ppl-2025
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
